### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by thejameskyle**

### CODE REVIEW

**Comment by shinnn** [comment]
This package already uses [`files`](https://docs.npmjs.com/files/package.json#files) field instead. https://github.com/deoxxa/duplexer2/blob/7d008c10499de01ba85636b5f77085ced015c37a/package.json#L5-L7

**Comment by thejameskyle** [comment]
Weird, your test directory is being included for me

**Comment by shinnn** [comment]
```
$ node -v
> v6.0.0

$ npm -v
> 3.8.8

$ npm install --save duplexer2
...

$ npm ls duplexer2
> test-proj@1.0.0 /Users/Shinnosuke/github/test-proj
> └── duplexer2@0.1.4 

$ ls node_modules/duplexer2
> LICENSE.md    README.md     index.js      package.json
```

For me, the test directory is successfully excluded.

@thejameskyle Which version of `duplexer2` are you trying to install?

**Comment by shinnn** [comment]
Or, maybe you use a non-npm package manager?

**Comment by thejameskyle** [comment]
Oh, older version of duplexer2. damn these dependency trees

**Comment by shinnn** [comment]
Wow, really [hardworking](https://github.com/thejameskyle?tab=contributions&from=2016-05-01). I agree to exclude test files form the published packages and appreciate those pull requests.

However, IMHO, I think whitelist (`files` field) is maintainable much easier than blacklist (.npmignore).

**Pull request closed without merging**
