### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by TrySound**
No breaking changes

### CODE REVIEW

**Comment by zertosh** [comment]
@deoxxa the stream3 update would be really helpful for us over in browserify

**Comment by feross** [comment]
+1

**Comment by shinnn** [comment]
:+1: (and I opened a new issue to fix this https://github.com/deoxxa/duplexer2/issues/14)

**Comment by zertosh** [comment]
thanks @shinnn! can you publish this to npm please?

**Comment by zertosh** [comment]
Hey @shinnn, any chance you can get to publishing soon? This is holding up moving Browserify to streams 3

**Comment by shinnn** [comment]
@zertosh Sorry for the delay. [I just published v0.1.0](https://github.com/deoxxa/duplexer2/commit/af38f7b1229d53e343bc65a13c1fc780ea5c9178) an it's already available via npm. Note that v0.1.0 includes an important breaking change. https://github.com/deoxxa/duplexer2/commit/09b4f902835a1e4eb65c01f1145c28332b2b9a45

I'll add a change log to this project later.

**Pull request merged**
